/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ConfigureAndLoad_CONSTANTS_H
#define ConfigureAndLoad_CONSTANTS_H

#include "ConfigureAndLoad_types.h"

namespace siemens { namespace bt { namespace configureandload {

class ConfigureAndLoadConstants {
 public:
  ConfigureAndLoadConstants();

  std::string INTERFACE_VERSION;
  std::string CONFIGUREANDLOAD_HTTP_JSON_URI;
  std::string SOCKET_TCP_BIN;
  std::string SOCKET_HTTP_JSON;
};

extern const ConfigureAndLoadConstants g_ConfigureAndLoad_constants;

}}} // namespace

#endif
