/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Dali_constants.h"

namespace siemens { namespace bt { namespace dali {

const DaliConstants g_Dali_constants;

DaliConstants::DaliConstants() {
  INTERFACE_VERSION = "0.36.1";

  DALI_HTTP_JSON_URI = "/api/thrift/dali.json";

  SOCKET_TCP_BIN = "/tmp/t_dali_tcpbin.socket";

  SOCKET_HTTP_JSON = "/tmp/t_dali_httpjs.socket";

}

}}} // namespace

