/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Pllink_constants.h"

namespace siemens { namespace bt { namespace pllink {

const PllinkConstants g_Pllink_constants;

PllinkConstants::PllinkConstants() {
  INTERFACE_VERSION = "0.36.0";

  PLLINK_HTTP_JSON_URI = "/api/thrift/pllink.json";

  SOCKET_TCP_BIN = "/tmp/t_pllink_tcpbin.socket";

  SOCKET_HTTP_JSON = "/tmp/t_pllink_httpjs.socket";

}

}}} // namespace

