/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Txio_types.h"

#include <algorithm>

namespace siemens { namespace bt { namespace txio {

}}} // namespace
