// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace Trentino {
namespace Example {
namespace BasicCalculatorRemoteClient {
namespace protobuf {

void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto() {
  delete BasicCalculatorResponse::default_instance_;
  delete BasicCalculatorResponse_addResponse::default_instance_;
  delete BasicCalculatorResponse_addSimpleResponse::default_instance_;
  delete BasicCalculatorResponse_divideResponse::default_instance_;
  delete BasicCalculatorResponse_multiplyResponse::default_instance_;
  delete BasicCalculatorResponse_divide2Response::default_instance_;
  delete BasicCalculatorResponse_calculateAgeResponse::default_instance_;
}

void protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorTypes_2eproto();
  BasicCalculatorResponse::default_instance_ = new BasicCalculatorResponse();
  BasicCalculatorResponse_addResponse::default_instance_ = new BasicCalculatorResponse_addResponse();
  BasicCalculatorResponse_addSimpleResponse::default_instance_ = new BasicCalculatorResponse_addSimpleResponse();
  BasicCalculatorResponse_divideResponse::default_instance_ = new BasicCalculatorResponse_divideResponse();
  BasicCalculatorResponse_multiplyResponse::default_instance_ = new BasicCalculatorResponse_multiplyResponse();
  BasicCalculatorResponse_divide2Response::default_instance_ = new BasicCalculatorResponse_divide2Response();
  BasicCalculatorResponse_calculateAgeResponse::default_instance_ = new BasicCalculatorResponse_calculateAgeResponse();
  BasicCalculatorResponse::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_addResponse::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_addSimpleResponse::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_divideResponse::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_multiplyResponse::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_divide2Response::default_instance_->InitAsDefaultInstance();
  BasicCalculatorResponse_calculateAgeResponse::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto {
  StaticDescriptorInitializer_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto() {
    protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();
  }
} static_descriptor_initializer_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int BasicCalculatorResponse_addResponse::kAddResponseFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_addResponse::BasicCalculatorResponse_addResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_addResponse::InitAsDefaultInstance() {
  addresponse_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::default_instance());
}

BasicCalculatorResponse_addResponse::BasicCalculatorResponse_addResponse(const BasicCalculatorResponse_addResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_addResponse::SharedCtor() {
  _cached_size_ = 0;
  addresponse_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_addResponse::~BasicCalculatorResponse_addResponse() {
  SharedDtor();
}

void BasicCalculatorResponse_addResponse::SharedDtor() {
  if (this != default_instance_) {
    delete addresponse_;
  }
}

void BasicCalculatorResponse_addResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_addResponse& BasicCalculatorResponse_addResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_addResponse* BasicCalculatorResponse_addResponse::default_instance_ = NULL;

BasicCalculatorResponse_addResponse* BasicCalculatorResponse_addResponse::New() const {
  return new BasicCalculatorResponse_addResponse;
}

void BasicCalculatorResponse_addResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_addresponse()) {
      if (addresponse_ != NULL) addresponse_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_addResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber addResponse = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addresponse()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_addResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber addResponse = 1;
  if (has_addresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->addresponse(), output);
  }
  
}

int BasicCalculatorResponse_addResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber addResponse = 1;
    if (has_addresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->addresponse());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_addResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_addResponse*>(&from));
}

void BasicCalculatorResponse_addResponse::MergeFrom(const BasicCalculatorResponse_addResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_addresponse()) {
      mutable_addresponse()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::MergeFrom(from.addresponse());
    }
  }
}

void BasicCalculatorResponse_addResponse::CopyFrom(const BasicCalculatorResponse_addResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_addResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_addResponse::Swap(BasicCalculatorResponse_addResponse* other) {
  if (other != this) {
    std::swap(addresponse_, other->addresponse_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_addResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addResponse";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse_addSimpleResponse::kAddSimpleResponseFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_addSimpleResponse::BasicCalculatorResponse_addSimpleResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_addSimpleResponse::InitAsDefaultInstance() {
}

BasicCalculatorResponse_addSimpleResponse::BasicCalculatorResponse_addSimpleResponse(const BasicCalculatorResponse_addSimpleResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_addSimpleResponse::SharedCtor() {
  _cached_size_ = 0;
  addsimpleresponse_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_addSimpleResponse::~BasicCalculatorResponse_addSimpleResponse() {
  SharedDtor();
}

void BasicCalculatorResponse_addSimpleResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BasicCalculatorResponse_addSimpleResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_addSimpleResponse& BasicCalculatorResponse_addSimpleResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_addSimpleResponse* BasicCalculatorResponse_addSimpleResponse::default_instance_ = NULL;

BasicCalculatorResponse_addSimpleResponse* BasicCalculatorResponse_addSimpleResponse::New() const {
  return new BasicCalculatorResponse_addSimpleResponse;
}

void BasicCalculatorResponse_addSimpleResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    addsimpleresponse_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_addSimpleResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 addSimpleResponse = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &addsimpleresponse_)));
          set_has_addsimpleresponse();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_addSimpleResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 addSimpleResponse = 1;
  if (has_addsimpleresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->addsimpleresponse(), output);
  }
  
}

int BasicCalculatorResponse_addSimpleResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 addSimpleResponse = 1;
    if (has_addsimpleresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->addsimpleresponse());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_addSimpleResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_addSimpleResponse*>(&from));
}

void BasicCalculatorResponse_addSimpleResponse::MergeFrom(const BasicCalculatorResponse_addSimpleResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_addsimpleresponse()) {
      set_addsimpleresponse(from.addsimpleresponse());
    }
  }
}

void BasicCalculatorResponse_addSimpleResponse::CopyFrom(const BasicCalculatorResponse_addSimpleResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_addSimpleResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_addSimpleResponse::Swap(BasicCalculatorResponse_addSimpleResponse* other) {
  if (other != this) {
    std::swap(addsimpleresponse_, other->addsimpleresponse_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_addSimpleResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addSimpleResponse";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse_divideResponse::kDivideResponseFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_divideResponse::BasicCalculatorResponse_divideResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_divideResponse::InitAsDefaultInstance() {
  divideresponse_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::default_instance());
}

BasicCalculatorResponse_divideResponse::BasicCalculatorResponse_divideResponse(const BasicCalculatorResponse_divideResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_divideResponse::SharedCtor() {
  _cached_size_ = 0;
  divideresponse_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_divideResponse::~BasicCalculatorResponse_divideResponse() {
  SharedDtor();
}

void BasicCalculatorResponse_divideResponse::SharedDtor() {
  if (this != default_instance_) {
    delete divideresponse_;
  }
}

void BasicCalculatorResponse_divideResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_divideResponse& BasicCalculatorResponse_divideResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_divideResponse* BasicCalculatorResponse_divideResponse::default_instance_ = NULL;

BasicCalculatorResponse_divideResponse* BasicCalculatorResponse_divideResponse::New() const {
  return new BasicCalculatorResponse_divideResponse;
}

void BasicCalculatorResponse_divideResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_divideresponse()) {
      if (divideresponse_ != NULL) divideresponse_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_divideResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divideResponse = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_divideresponse()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_divideResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divideResponse = 1;
  if (has_divideresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->divideresponse(), output);
  }
  
}

int BasicCalculatorResponse_divideResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divideResponse = 1;
    if (has_divideresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->divideresponse());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_divideResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_divideResponse*>(&from));
}

void BasicCalculatorResponse_divideResponse::MergeFrom(const BasicCalculatorResponse_divideResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_divideresponse()) {
      mutable_divideresponse()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::MergeFrom(from.divideresponse());
    }
  }
}

void BasicCalculatorResponse_divideResponse::CopyFrom(const BasicCalculatorResponse_divideResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_divideResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_divideResponse::Swap(BasicCalculatorResponse_divideResponse* other) {
  if (other != this) {
    std::swap(divideresponse_, other->divideresponse_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_divideResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divideResponse";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse_multiplyResponse::kCFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_multiplyResponse::BasicCalculatorResponse_multiplyResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_multiplyResponse::InitAsDefaultInstance() {
  c_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::default_instance());
}

BasicCalculatorResponse_multiplyResponse::BasicCalculatorResponse_multiplyResponse(const BasicCalculatorResponse_multiplyResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_multiplyResponse::SharedCtor() {
  _cached_size_ = 0;
  c_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_multiplyResponse::~BasicCalculatorResponse_multiplyResponse() {
  SharedDtor();
}

void BasicCalculatorResponse_multiplyResponse::SharedDtor() {
  if (this != default_instance_) {
    delete c_;
  }
}

void BasicCalculatorResponse_multiplyResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_multiplyResponse& BasicCalculatorResponse_multiplyResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_multiplyResponse* BasicCalculatorResponse_multiplyResponse::default_instance_ = NULL;

BasicCalculatorResponse_multiplyResponse* BasicCalculatorResponse_multiplyResponse::New() const {
  return new BasicCalculatorResponse_multiplyResponse;
}

void BasicCalculatorResponse_multiplyResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_c()) {
      if (c_ != NULL) c_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_multiplyResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber c = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_c()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_multiplyResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber c = 1;
  if (has_c()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->c(), output);
  }
  
}

int BasicCalculatorResponse_multiplyResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber c = 1;
    if (has_c()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->c());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_multiplyResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_multiplyResponse*>(&from));
}

void BasicCalculatorResponse_multiplyResponse::MergeFrom(const BasicCalculatorResponse_multiplyResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_c()) {
      mutable_c()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::MergeFrom(from.c());
    }
  }
}

void BasicCalculatorResponse_multiplyResponse::CopyFrom(const BasicCalculatorResponse_multiplyResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_multiplyResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_multiplyResponse::Swap(BasicCalculatorResponse_multiplyResponse* other) {
  if (other != this) {
    std::swap(c_, other->c_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_multiplyResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.multiplyResponse";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse_divide2Response::kDivide2ResponseFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_divide2Response::BasicCalculatorResponse_divide2Response()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_divide2Response::InitAsDefaultInstance() {
  divide2response_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::default_instance());
}

BasicCalculatorResponse_divide2Response::BasicCalculatorResponse_divide2Response(const BasicCalculatorResponse_divide2Response& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_divide2Response::SharedCtor() {
  _cached_size_ = 0;
  divide2response_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_divide2Response::~BasicCalculatorResponse_divide2Response() {
  SharedDtor();
}

void BasicCalculatorResponse_divide2Response::SharedDtor() {
  if (this != default_instance_) {
    delete divide2response_;
  }
}

void BasicCalculatorResponse_divide2Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_divide2Response& BasicCalculatorResponse_divide2Response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_divide2Response* BasicCalculatorResponse_divide2Response::default_instance_ = NULL;

BasicCalculatorResponse_divide2Response* BasicCalculatorResponse_divide2Response::New() const {
  return new BasicCalculatorResponse_divide2Response;
}

void BasicCalculatorResponse_divide2Response::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_divide2response()) {
      if (divide2response_ != NULL) divide2response_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_divide2Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divide2Response = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_divide2response()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_divide2Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divide2Response = 1;
  if (has_divide2response()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->divide2response(), output);
  }
  
}

int BasicCalculatorResponse_divide2Response::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber divide2Response = 1;
    if (has_divide2response()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->divide2response());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_divide2Response::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_divide2Response*>(&from));
}

void BasicCalculatorResponse_divide2Response::MergeFrom(const BasicCalculatorResponse_divide2Response& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_divide2response()) {
      mutable_divide2response()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::MergeFrom(from.divide2response());
    }
  }
}

void BasicCalculatorResponse_divide2Response::CopyFrom(const BasicCalculatorResponse_divide2Response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_divide2Response::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_divide2Response::Swap(BasicCalculatorResponse_divide2Response* other) {
  if (other != this) {
    std::swap(divide2response_, other->divide2response_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_divide2Response::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divide2Response";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse_calculateAgeResponse::kCalculateAgeResponseFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse_calculateAgeResponse::BasicCalculatorResponse_calculateAgeResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse_calculateAgeResponse::InitAsDefaultInstance() {
}

BasicCalculatorResponse_calculateAgeResponse::BasicCalculatorResponse_calculateAgeResponse(const BasicCalculatorResponse_calculateAgeResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse_calculateAgeResponse::SharedCtor() {
  _cached_size_ = 0;
  calculateageresponse_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse_calculateAgeResponse::~BasicCalculatorResponse_calculateAgeResponse() {
  SharedDtor();
}

void BasicCalculatorResponse_calculateAgeResponse::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BasicCalculatorResponse_calculateAgeResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse_calculateAgeResponse& BasicCalculatorResponse_calculateAgeResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse_calculateAgeResponse* BasicCalculatorResponse_calculateAgeResponse::default_instance_ = NULL;

BasicCalculatorResponse_calculateAgeResponse* BasicCalculatorResponse_calculateAgeResponse::New() const {
  return new BasicCalculatorResponse_calculateAgeResponse;
}

void BasicCalculatorResponse_calculateAgeResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    calculateageresponse_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse_calculateAgeResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 calculateAgeResponse = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &calculateageresponse_)));
          set_has_calculateageresponse();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse_calculateAgeResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional uint32 calculateAgeResponse = 1;
  if (has_calculateageresponse()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->calculateageresponse(), output);
  }
  
}

int BasicCalculatorResponse_calculateAgeResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 calculateAgeResponse = 1;
    if (has_calculateageresponse()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->calculateageresponse());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse_calculateAgeResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse_calculateAgeResponse*>(&from));
}

void BasicCalculatorResponse_calculateAgeResponse::MergeFrom(const BasicCalculatorResponse_calculateAgeResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_calculateageresponse()) {
      set_calculateageresponse(from.calculateageresponse());
    }
  }
}

void BasicCalculatorResponse_calculateAgeResponse::CopyFrom(const BasicCalculatorResponse_calculateAgeResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse_calculateAgeResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse_calculateAgeResponse::Swap(BasicCalculatorResponse_calculateAgeResponse* other) {
  if (other != this) {
    std::swap(calculateageresponse_, other->calculateageresponse_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse_calculateAgeResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.calculateAgeResponse";
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int BasicCalculatorResponse::kAddResponseObjectFieldNumber;
const int BasicCalculatorResponse::kAddSimpleResponseObjectFieldNumber;
const int BasicCalculatorResponse::kDivideResponseObjectFieldNumber;
const int BasicCalculatorResponse::kMultiplyResponseObjectFieldNumber;
const int BasicCalculatorResponse::kDivide2ResponseObjectFieldNumber;
const int BasicCalculatorResponse::kCalculateAgeResponseObjectFieldNumber;
#endif  // !_MSC_VER

BasicCalculatorResponse::BasicCalculatorResponse()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void BasicCalculatorResponse::InitAsDefaultInstance() {
  addresponseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addResponse*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addResponse::default_instance());
  addsimpleresponseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addSimpleResponse*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addSimpleResponse::default_instance());
  divideresponseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divideResponse*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divideResponse::default_instance());
  multiplyresponseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_multiplyResponse*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_multiplyResponse::default_instance());
  divide2responseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divide2Response*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divide2Response::default_instance());
  calculateageresponseobject_ = const_cast< ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_calculateAgeResponse*>(&::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_calculateAgeResponse::default_instance());
}

BasicCalculatorResponse::BasicCalculatorResponse(const BasicCalculatorResponse& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void BasicCalculatorResponse::SharedCtor() {
  _cached_size_ = 0;
  addresponseobject_ = NULL;
  addsimpleresponseobject_ = NULL;
  divideresponseobject_ = NULL;
  multiplyresponseobject_ = NULL;
  divide2responseobject_ = NULL;
  calculateageresponseobject_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BasicCalculatorResponse::~BasicCalculatorResponse() {
  SharedDtor();
}

void BasicCalculatorResponse::SharedDtor() {
  if (this != default_instance_) {
    delete addresponseobject_;
    delete addsimpleresponseobject_;
    delete divideresponseobject_;
    delete multiplyresponseobject_;
    delete divide2responseobject_;
    delete calculateageresponseobject_;
  }
}

void BasicCalculatorResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const BasicCalculatorResponse& BasicCalculatorResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorResponse_2eproto();  return *default_instance_;
}

BasicCalculatorResponse* BasicCalculatorResponse::default_instance_ = NULL;

BasicCalculatorResponse* BasicCalculatorResponse::New() const {
  return new BasicCalculatorResponse;
}

void BasicCalculatorResponse::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_addresponseobject()) {
      if (addresponseobject_ != NULL) addresponseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addResponse::Clear();
    }
    if (has_addsimpleresponseobject()) {
      if (addsimpleresponseobject_ != NULL) addsimpleresponseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addSimpleResponse::Clear();
    }
    if (has_divideresponseobject()) {
      if (divideresponseobject_ != NULL) divideresponseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divideResponse::Clear();
    }
    if (has_multiplyresponseobject()) {
      if (multiplyresponseobject_ != NULL) multiplyresponseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_multiplyResponse::Clear();
    }
    if (has_divide2responseobject()) {
      if (divide2responseobject_ != NULL) divide2responseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divide2Response::Clear();
    }
    if (has_calculateageresponseobject()) {
      if (calculateageresponseobject_ != NULL) calculateageresponseobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_calculateAgeResponse::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool BasicCalculatorResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addResponse addResponseObject = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addresponseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_addSimpleResponseObject;
        break;
      }
      
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addSimpleResponse addSimpleResponseObject = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_addSimpleResponseObject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_addsimpleresponseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_divideResponseObject;
        break;
      }
      
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divideResponse divideResponseObject = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_divideResponseObject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_divideresponseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_multiplyResponseObject;
        break;
      }
      
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.multiplyResponse multiplyResponseObject = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_multiplyResponseObject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_multiplyresponseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_divide2ResponseObject;
        break;
      }
      
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divide2Response divide2ResponseObject = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_divide2ResponseObject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_divide2responseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_calculateAgeResponseObject;
        break;
      }
      
      // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.calculateAgeResponse calculateAgeResponseObject = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_calculateAgeResponseObject:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_calculateageresponseobject()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BasicCalculatorResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addResponse addResponseObject = 1;
  if (has_addresponseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->addresponseobject(), output);
  }
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addSimpleResponse addSimpleResponseObject = 2;
  if (has_addsimpleresponseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->addsimpleresponseobject(), output);
  }
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divideResponse divideResponseObject = 3;
  if (has_divideresponseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3, this->divideresponseobject(), output);
  }
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.multiplyResponse multiplyResponseObject = 4;
  if (has_multiplyresponseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->multiplyresponseobject(), output);
  }
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divide2Response divide2ResponseObject = 5;
  if (has_divide2responseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->divide2responseobject(), output);
  }
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.calculateAgeResponse calculateAgeResponseObject = 6;
  if (has_calculateageresponseobject()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      6, this->calculateageresponseobject(), output);
  }
  
}

int BasicCalculatorResponse::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addResponse addResponseObject = 1;
    if (has_addresponseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->addresponseobject());
    }
    
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.addSimpleResponse addSimpleResponseObject = 2;
    if (has_addsimpleresponseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->addsimpleresponseobject());
    }
    
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divideResponse divideResponseObject = 3;
    if (has_divideresponseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->divideresponseobject());
    }
    
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.multiplyResponse multiplyResponseObject = 4;
    if (has_multiplyresponseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->multiplyresponseobject());
    }
    
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.divide2Response divide2ResponseObject = 5;
    if (has_divide2responseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->divide2responseobject());
    }
    
    // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse.calculateAgeResponse calculateAgeResponseObject = 6;
    if (has_calculateageresponseobject()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->calculateageresponseobject());
    }
    
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BasicCalculatorResponse::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const BasicCalculatorResponse*>(&from));
}

void BasicCalculatorResponse::MergeFrom(const BasicCalculatorResponse& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_addresponseobject()) {
      mutable_addresponseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addResponse::MergeFrom(from.addresponseobject());
    }
    if (from.has_addsimpleresponseobject()) {
      mutable_addsimpleresponseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_addSimpleResponse::MergeFrom(from.addsimpleresponseobject());
    }
    if (from.has_divideresponseobject()) {
      mutable_divideresponseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divideResponse::MergeFrom(from.divideresponseobject());
    }
    if (from.has_multiplyresponseobject()) {
      mutable_multiplyresponseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_multiplyResponse::MergeFrom(from.multiplyresponseobject());
    }
    if (from.has_divide2responseobject()) {
      mutable_divide2responseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_divide2Response::MergeFrom(from.divide2responseobject());
    }
    if (from.has_calculateageresponseobject()) {
      mutable_calculateageresponseobject()->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorResponse_calculateAgeResponse::MergeFrom(from.calculateageresponseobject());
    }
  }
}

void BasicCalculatorResponse::CopyFrom(const BasicCalculatorResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BasicCalculatorResponse::IsInitialized() const {
  
  return true;
}

void BasicCalculatorResponse::Swap(BasicCalculatorResponse* other) {
  if (other != this) {
    std::swap(addresponseobject_, other->addresponseobject_);
    std::swap(addsimpleresponseobject_, other->addsimpleresponseobject_);
    std::swap(divideresponseobject_, other->divideresponseobject_);
    std::swap(multiplyresponseobject_, other->multiplyresponseobject_);
    std::swap(divide2responseobject_, other->divide2responseobject_);
    std::swap(calculateageresponseobject_, other->calculateageresponseobject_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string BasicCalculatorResponse::GetTypeName() const {
  return "Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorResponse";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace BasicCalculatorRemoteClient
}  // namespace Example
}  // namespace Trentino

// @@protoc_insertion_point(global_scope)
