// ****************************************************************************
// Generated by Trengen. Do not modify
// **************************************************************************** 

//header
#include "TrentinoGenContributionInfo.h"

#include "TrentinoGenProxiesWrappers.h"


using namespace Trentino::Gen;

extern "C" TRENTINO_DLLEXPORT Trentino::Core::TrentinoContributionInfo* TRENTINO_CDECL getContributionInfo()
{
 return new Trentino::Gen::GenContributionInfo();
}


//constructor and destructor implementation
CONTRIBUTIONINFO_CPP_CDTOR(Gen);

TRENTINO_DLLEXPORT  Trentino::Invocation::ServiceInvocationWrapperBase* TRENTINO_CDECL GenContributionInfo::getServiceInvocationWrapperByClassName( const std::string& /*className*/ )
{
   return nullptr;
}
   
static BindingHelperFactoryList bindingHelperFactories;
  
TRENTINO_DLLEXPORT  Trentino::Binding::BindingHelperBase* TRENTINO_CDECL GenContributionInfo::getBindingHelperByBindingIdAndClassName( const std::string& bindingId,const std::string& className )
 {
 BindingHelperFactoryList::iterator it ;
 for(it = bindingHelperFactories.begin();it !=bindingHelperFactories.end();++it){
    BindingHelperFactory factory = *it;
    if(factory.mBindingId == bindingId && factory.mClassName == className){
       return factory.getBindingHelper();
       }
    }
  return nullptr;
 } 
 
  TRENTINO_DLLEXPORT  const char* TRENTINO_CDECL GenContributionInfo::getAllDeclaredBindings() const
 {
 	
    return "binding.sca";
 }