// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest.proto

#ifndef PROTOBUF_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto__INCLUDED
#define PROTOBUF_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorTypes.pb.h"
// @@protoc_insertion_point(includes)

namespace Trentino {
namespace Example {
namespace BasicCalculatorRemoteClient {
namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();

class BasicCalculatorRequest;
class BasicCalculatorRequest_addRequest;
class BasicCalculatorRequest_addSimpleRequest;
class BasicCalculatorRequest_divideRequest;
class BasicCalculatorRequest_multiplyRequest;
class BasicCalculatorRequest_divide2Request;
class BasicCalculatorRequest_calculateAgeRequest;

// ===================================================================

class BasicCalculatorRequest_addRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_addRequest();
  virtual ~BasicCalculatorRequest_addRequest();
  
  BasicCalculatorRequest_addRequest(const BasicCalculatorRequest_addRequest& from);
  
  inline BasicCalculatorRequest_addRequest& operator=(const BasicCalculatorRequest_addRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_addRequest& default_instance();
  
  void Swap(BasicCalculatorRequest_addRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_addRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_addRequest& from);
  void MergeFrom(const BasicCalculatorRequest_addRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& a() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_a();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_a();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& b() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_b();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_b();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* a_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* b_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_addRequest* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest_addSimpleRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_addSimpleRequest();
  virtual ~BasicCalculatorRequest_addSimpleRequest();
  
  BasicCalculatorRequest_addSimpleRequest(const BasicCalculatorRequest_addSimpleRequest& from);
  
  inline BasicCalculatorRequest_addSimpleRequest& operator=(const BasicCalculatorRequest_addSimpleRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_addSimpleRequest& default_instance();
  
  void Swap(BasicCalculatorRequest_addSimpleRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_addSimpleRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_addSimpleRequest& from);
  void MergeFrom(const BasicCalculatorRequest_addSimpleRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline ::google::protobuf::int32 a() const;
  inline void set_a(::google::protobuf::int32 value);
  
  // optional int32 b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addSimpleRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();
  
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_addSimpleRequest* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest_divideRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_divideRequest();
  virtual ~BasicCalculatorRequest_divideRequest();
  
  BasicCalculatorRequest_divideRequest(const BasicCalculatorRequest_divideRequest& from);
  
  inline BasicCalculatorRequest_divideRequest& operator=(const BasicCalculatorRequest_divideRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_divideRequest& default_instance();
  
  void Swap(BasicCalculatorRequest_divideRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_divideRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_divideRequest& from);
  void MergeFrom(const BasicCalculatorRequest_divideRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& a() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_a();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_a();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& b() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_b();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_b();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divideRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* a_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* b_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_divideRequest* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest_multiplyRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_multiplyRequest();
  virtual ~BasicCalculatorRequest_multiplyRequest();
  
  BasicCalculatorRequest_multiplyRequest(const BasicCalculatorRequest_multiplyRequest& from);
  
  inline BasicCalculatorRequest_multiplyRequest& operator=(const BasicCalculatorRequest_multiplyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_multiplyRequest& default_instance();
  
  void Swap(BasicCalculatorRequest_multiplyRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_multiplyRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_multiplyRequest& from);
  void MergeFrom(const BasicCalculatorRequest_multiplyRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
  inline bool has_a() const;
  inline void clear_a();
  static const int kAFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& a() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_a();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_a();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 2;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& b() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_b();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_b();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber c = 3;
  inline bool has_c() const;
  inline void clear_c();
  static const int kCFieldNumber = 3;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& c() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* mutable_c();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* release_c();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.multiplyRequest)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_b();
  inline void clear_has_b();
  inline void set_has_c();
  inline void clear_has_c();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* a_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* b_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* c_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_multiplyRequest* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest_divide2Request : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_divide2Request();
  virtual ~BasicCalculatorRequest_divide2Request();
  
  BasicCalculatorRequest_divide2Request(const BasicCalculatorRequest_divide2Request& from);
  
  inline BasicCalculatorRequest_divide2Request& operator=(const BasicCalculatorRequest_divide2Request& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_divide2Request& default_instance();
  
  void Swap(BasicCalculatorRequest_divide2Request* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_divide2Request* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_divide2Request& from);
  void MergeFrom(const BasicCalculatorRequest_divide2Request& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_TupleComplexNumber tuple = 1;
  inline bool has_tuple() const;
  inline void clear_tuple();
  static const int kTupleFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber& tuple() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* mutable_tuple();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* release_tuple();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divide2Request)
 private:
  inline void set_has_tuple();
  inline void clear_has_tuple();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* tuple_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_divide2Request* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest_calculateAgeRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest_calculateAgeRequest();
  virtual ~BasicCalculatorRequest_calculateAgeRequest();
  
  BasicCalculatorRequest_calculateAgeRequest(const BasicCalculatorRequest_calculateAgeRequest& from);
  
  inline BasicCalculatorRequest_calculateAgeRequest& operator=(const BasicCalculatorRequest_calculateAgeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest_calculateAgeRequest& default_instance();
  
  void Swap(BasicCalculatorRequest_calculateAgeRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest_calculateAgeRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest_calculateAgeRequest& from);
  void MergeFrom(const BasicCalculatorRequest_calculateAgeRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_Person person = 1;
  inline bool has_person() const;
  inline void clear_person();
  static const int kPersonFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person& person() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* mutable_person();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* release_person();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.calculateAgeRequest)
 private:
  inline void set_has_person();
  inline void clear_has_person();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* person_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest_calculateAgeRequest* default_instance_;
};
// -------------------------------------------------------------------

class BasicCalculatorRequest : public ::google::protobuf::MessageLite {
 public:
  BasicCalculatorRequest();
  virtual ~BasicCalculatorRequest();
  
  BasicCalculatorRequest(const BasicCalculatorRequest& from);
  
  inline BasicCalculatorRequest& operator=(const BasicCalculatorRequest& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BasicCalculatorRequest& default_instance();
  
  void Swap(BasicCalculatorRequest* other);
  
  // implements Message ----------------------------------------------
  
  BasicCalculatorRequest* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BasicCalculatorRequest& from);
  void MergeFrom(const BasicCalculatorRequest& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  typedef BasicCalculatorRequest_addRequest addRequest;
  typedef BasicCalculatorRequest_addSimpleRequest addSimpleRequest;
  typedef BasicCalculatorRequest_divideRequest divideRequest;
  typedef BasicCalculatorRequest_multiplyRequest multiplyRequest;
  typedef BasicCalculatorRequest_divide2Request divide2Request;
  typedef BasicCalculatorRequest_calculateAgeRequest calculateAgeRequest;
  
  // accessors -------------------------------------------------------
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addRequest addRequestObject = 1;
  inline bool has_addrequestobject() const;
  inline void clear_addrequestobject();
  static const int kAddRequestObjectFieldNumber = 1;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest& addrequestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* mutable_addrequestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* release_addrequestobject();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addSimpleRequest addSimpleRequestObject = 2;
  inline bool has_addsimplerequestobject() const;
  inline void clear_addsimplerequestobject();
  static const int kAddSimpleRequestObjectFieldNumber = 2;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest& addsimplerequestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* mutable_addsimplerequestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* release_addsimplerequestobject();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divideRequest divideRequestObject = 3;
  inline bool has_dividerequestobject() const;
  inline void clear_dividerequestobject();
  static const int kDivideRequestObjectFieldNumber = 3;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest& dividerequestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* mutable_dividerequestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* release_dividerequestobject();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.multiplyRequest multiplyRequestObject = 4;
  inline bool has_multiplyrequestobject() const;
  inline void clear_multiplyrequestobject();
  static const int kMultiplyRequestObjectFieldNumber = 4;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest& multiplyrequestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* mutable_multiplyrequestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* release_multiplyrequestobject();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divide2Request divide2RequestObject = 5;
  inline bool has_divide2requestobject() const;
  inline void clear_divide2requestobject();
  static const int kDivide2RequestObjectFieldNumber = 5;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request& divide2requestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* mutable_divide2requestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* release_divide2requestobject();
  
  // optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.calculateAgeRequest calculateAgeRequestObject = 6;
  inline bool has_calculateagerequestobject() const;
  inline void clear_calculateagerequestobject();
  static const int kCalculateAgeRequestObjectFieldNumber = 6;
  inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest& calculateagerequestobject() const;
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* mutable_calculateagerequestobject();
  inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* release_calculateagerequestobject();
  
  // @@protoc_insertion_point(class_scope:Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest)
 private:
  inline void set_has_addrequestobject();
  inline void clear_has_addrequestobject();
  inline void set_has_addsimplerequestobject();
  inline void clear_has_addsimplerequestobject();
  inline void set_has_dividerequestobject();
  inline void clear_has_dividerequestobject();
  inline void set_has_multiplyrequestobject();
  inline void clear_has_multiplyrequestobject();
  inline void set_has_divide2requestobject();
  inline void clear_has_divide2requestobject();
  inline void set_has_calculateagerequestobject();
  inline void clear_has_calculateagerequestobject();
  
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* addrequestobject_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* addsimplerequestobject_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* dividerequestobject_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* multiplyrequestobject_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* divide2requestobject_;
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* calculateagerequestobject_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_AssignDesc_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  friend void protobuf_ShutdownFile_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto();
  
  void InitAsDefaultInstance();
  static BasicCalculatorRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// BasicCalculatorRequest_addRequest

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
inline bool BasicCalculatorRequest_addRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_addRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_addRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_addRequest::clear_a() {
  if (a_ != NULL) a_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_a();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_addRequest::a() const {
  return a_ != NULL ? *a_ : *default_instance_->a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_addRequest::mutable_a() {
  set_has_a();
  if (a_ == NULL) a_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_addRequest::release_a() {
  clear_has_a();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = a_;
  a_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
inline bool BasicCalculatorRequest_addRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BasicCalculatorRequest_addRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BasicCalculatorRequest_addRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BasicCalculatorRequest_addRequest::clear_b() {
  if (b_ != NULL) b_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_b();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_addRequest::b() const {
  return b_ != NULL ? *b_ : *default_instance_->b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_addRequest::mutable_b() {
  set_has_b();
  if (b_ == NULL) b_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_addRequest::release_b() {
  clear_has_b();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = b_;
  b_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest_addSimpleRequest

// optional int32 a = 1;
inline bool BasicCalculatorRequest_addSimpleRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_addSimpleRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_addSimpleRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_addSimpleRequest::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 BasicCalculatorRequest_addSimpleRequest::a() const {
  return a_;
}
inline void BasicCalculatorRequest_addSimpleRequest::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
}

// optional int32 b = 2;
inline bool BasicCalculatorRequest_addSimpleRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BasicCalculatorRequest_addSimpleRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BasicCalculatorRequest_addSimpleRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BasicCalculatorRequest_addSimpleRequest::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 BasicCalculatorRequest_addSimpleRequest::b() const {
  return b_;
}
inline void BasicCalculatorRequest_addSimpleRequest::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest_divideRequest

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
inline bool BasicCalculatorRequest_divideRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_divideRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_divideRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_divideRequest::clear_a() {
  if (a_ != NULL) a_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_a();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_divideRequest::a() const {
  return a_ != NULL ? *a_ : *default_instance_->a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_divideRequest::mutable_a() {
  set_has_a();
  if (a_ == NULL) a_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_divideRequest::release_a() {
  clear_has_a();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = a_;
  a_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
inline bool BasicCalculatorRequest_divideRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BasicCalculatorRequest_divideRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BasicCalculatorRequest_divideRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BasicCalculatorRequest_divideRequest::clear_b() {
  if (b_ != NULL) b_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_b();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_divideRequest::b() const {
  return b_ != NULL ? *b_ : *default_instance_->b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_divideRequest::mutable_b() {
  set_has_b();
  if (b_ == NULL) b_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_divideRequest::release_b() {
  clear_has_b();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = b_;
  b_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest_multiplyRequest

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber a = 1;
inline bool BasicCalculatorRequest_multiplyRequest::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_multiplyRequest::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_a() {
  if (a_ != NULL) a_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_a();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_multiplyRequest::a() const {
  return a_ != NULL ? *a_ : *default_instance_->a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::mutable_a() {
  set_has_a();
  if (a_ == NULL) a_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return a_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::release_a() {
  clear_has_a();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = a_;
  a_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber b = 2;
inline bool BasicCalculatorRequest_multiplyRequest::has_b() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BasicCalculatorRequest_multiplyRequest::set_has_b() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_has_b() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_b() {
  if (b_ != NULL) b_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_b();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_multiplyRequest::b() const {
  return b_ != NULL ? *b_ : *default_instance_->b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::mutable_b() {
  set_has_b();
  if (b_ == NULL) b_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return b_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::release_b() {
  clear_has_b();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = b_;
  b_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_ComplexNumber c = 3;
inline bool BasicCalculatorRequest_multiplyRequest::has_c() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BasicCalculatorRequest_multiplyRequest::set_has_c() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_has_c() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BasicCalculatorRequest_multiplyRequest::clear_c() {
  if (c_ != NULL) c_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber::Clear();
  clear_has_c();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber& BasicCalculatorRequest_multiplyRequest::c() const {
  return c_ != NULL ? *c_ : *default_instance_->c_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::mutable_c() {
  set_has_c();
  if (c_ == NULL) c_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber;
  return c_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* BasicCalculatorRequest_multiplyRequest::release_c() {
  clear_has_c();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_ComplexNumber* temp = c_;
  c_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest_divide2Request

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_TupleComplexNumber tuple = 1;
inline bool BasicCalculatorRequest_divide2Request::has_tuple() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_divide2Request::set_has_tuple() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_divide2Request::clear_has_tuple() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_divide2Request::clear_tuple() {
  if (tuple_ != NULL) tuple_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber::Clear();
  clear_has_tuple();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber& BasicCalculatorRequest_divide2Request::tuple() const {
  return tuple_ != NULL ? *tuple_ : *default_instance_->tuple_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* BasicCalculatorRequest_divide2Request::mutable_tuple() {
  set_has_tuple();
  if (tuple_ == NULL) tuple_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber;
  return tuple_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* BasicCalculatorRequest_divide2Request::release_tuple() {
  clear_has_tuple();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_TupleComplexNumber* temp = tuple_;
  tuple_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest_calculateAgeRequest

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.PB_Person person = 1;
inline bool BasicCalculatorRequest_calculateAgeRequest::has_person() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest_calculateAgeRequest::set_has_person() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest_calculateAgeRequest::clear_has_person() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest_calculateAgeRequest::clear_person() {
  if (person_ != NULL) person_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person::Clear();
  clear_has_person();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person& BasicCalculatorRequest_calculateAgeRequest::person() const {
  return person_ != NULL ? *person_ : *default_instance_->person_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* BasicCalculatorRequest_calculateAgeRequest::mutable_person() {
  set_has_person();
  if (person_ == NULL) person_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person;
  return person_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* BasicCalculatorRequest_calculateAgeRequest::release_person() {
  clear_has_person();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::PB_Person* temp = person_;
  person_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// BasicCalculatorRequest

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addRequest addRequestObject = 1;
inline bool BasicCalculatorRequest::has_addrequestobject() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BasicCalculatorRequest::set_has_addrequestobject() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BasicCalculatorRequest::clear_has_addrequestobject() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BasicCalculatorRequest::clear_addrequestobject() {
  if (addrequestobject_ != NULL) addrequestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest::Clear();
  clear_has_addrequestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest& BasicCalculatorRequest::addrequestobject() const {
  return addrequestobject_ != NULL ? *addrequestobject_ : *default_instance_->addrequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* BasicCalculatorRequest::mutable_addrequestobject() {
  set_has_addrequestobject();
  if (addrequestobject_ == NULL) addrequestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest;
  return addrequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* BasicCalculatorRequest::release_addrequestobject() {
  clear_has_addrequestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addRequest* temp = addrequestobject_;
  addrequestobject_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.addSimpleRequest addSimpleRequestObject = 2;
inline bool BasicCalculatorRequest::has_addsimplerequestobject() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BasicCalculatorRequest::set_has_addsimplerequestobject() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BasicCalculatorRequest::clear_has_addsimplerequestobject() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BasicCalculatorRequest::clear_addsimplerequestobject() {
  if (addsimplerequestobject_ != NULL) addsimplerequestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest::Clear();
  clear_has_addsimplerequestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest& BasicCalculatorRequest::addsimplerequestobject() const {
  return addsimplerequestobject_ != NULL ? *addsimplerequestobject_ : *default_instance_->addsimplerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* BasicCalculatorRequest::mutable_addsimplerequestobject() {
  set_has_addsimplerequestobject();
  if (addsimplerequestobject_ == NULL) addsimplerequestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest;
  return addsimplerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* BasicCalculatorRequest::release_addsimplerequestobject() {
  clear_has_addsimplerequestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_addSimpleRequest* temp = addsimplerequestobject_;
  addsimplerequestobject_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divideRequest divideRequestObject = 3;
inline bool BasicCalculatorRequest::has_dividerequestobject() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BasicCalculatorRequest::set_has_dividerequestobject() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BasicCalculatorRequest::clear_has_dividerequestobject() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BasicCalculatorRequest::clear_dividerequestobject() {
  if (dividerequestobject_ != NULL) dividerequestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest::Clear();
  clear_has_dividerequestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest& BasicCalculatorRequest::dividerequestobject() const {
  return dividerequestobject_ != NULL ? *dividerequestobject_ : *default_instance_->dividerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* BasicCalculatorRequest::mutable_dividerequestobject() {
  set_has_dividerequestobject();
  if (dividerequestobject_ == NULL) dividerequestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest;
  return dividerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* BasicCalculatorRequest::release_dividerequestobject() {
  clear_has_dividerequestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divideRequest* temp = dividerequestobject_;
  dividerequestobject_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.multiplyRequest multiplyRequestObject = 4;
inline bool BasicCalculatorRequest::has_multiplyrequestobject() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BasicCalculatorRequest::set_has_multiplyrequestobject() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BasicCalculatorRequest::clear_has_multiplyrequestobject() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BasicCalculatorRequest::clear_multiplyrequestobject() {
  if (multiplyrequestobject_ != NULL) multiplyrequestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest::Clear();
  clear_has_multiplyrequestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest& BasicCalculatorRequest::multiplyrequestobject() const {
  return multiplyrequestobject_ != NULL ? *multiplyrequestobject_ : *default_instance_->multiplyrequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* BasicCalculatorRequest::mutable_multiplyrequestobject() {
  set_has_multiplyrequestobject();
  if (multiplyrequestobject_ == NULL) multiplyrequestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest;
  return multiplyrequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* BasicCalculatorRequest::release_multiplyrequestobject() {
  clear_has_multiplyrequestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_multiplyRequest* temp = multiplyrequestobject_;
  multiplyrequestobject_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.divide2Request divide2RequestObject = 5;
inline bool BasicCalculatorRequest::has_divide2requestobject() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BasicCalculatorRequest::set_has_divide2requestobject() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BasicCalculatorRequest::clear_has_divide2requestobject() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BasicCalculatorRequest::clear_divide2requestobject() {
  if (divide2requestobject_ != NULL) divide2requestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request::Clear();
  clear_has_divide2requestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request& BasicCalculatorRequest::divide2requestobject() const {
  return divide2requestobject_ != NULL ? *divide2requestobject_ : *default_instance_->divide2requestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* BasicCalculatorRequest::mutable_divide2requestobject() {
  set_has_divide2requestobject();
  if (divide2requestobject_ == NULL) divide2requestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request;
  return divide2requestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* BasicCalculatorRequest::release_divide2requestobject() {
  clear_has_divide2requestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_divide2Request* temp = divide2requestobject_;
  divide2requestobject_ = NULL;
  return temp;
}

// optional .Trentino.Example.BasicCalculatorRemoteClient.protobuf.BasicCalculatorRequest.calculateAgeRequest calculateAgeRequestObject = 6;
inline bool BasicCalculatorRequest::has_calculateagerequestobject() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BasicCalculatorRequest::set_has_calculateagerequestobject() {
  _has_bits_[0] |= 0x00000020u;
}
inline void BasicCalculatorRequest::clear_has_calculateagerequestobject() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void BasicCalculatorRequest::clear_calculateagerequestobject() {
  if (calculateagerequestobject_ != NULL) calculateagerequestobject_->::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest::Clear();
  clear_has_calculateagerequestobject();
}
inline const ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest& BasicCalculatorRequest::calculateagerequestobject() const {
  return calculateagerequestobject_ != NULL ? *calculateagerequestobject_ : *default_instance_->calculateagerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* BasicCalculatorRequest::mutable_calculateagerequestobject() {
  set_has_calculateagerequestobject();
  if (calculateagerequestobject_ == NULL) calculateagerequestobject_ = new ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest;
  return calculateagerequestobject_;
}
inline ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* BasicCalculatorRequest::release_calculateagerequestobject() {
  clear_has_calculateagerequestobject();
  ::Trentino::Example::BasicCalculatorRemoteClient::protobuf::BasicCalculatorRequest_calculateAgeRequest* temp = calculateagerequestobject_;
  calculateagerequestobject_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf
}  // namespace BasicCalculatorRemoteClient
}  // namespace Example
}  // namespace Trentino

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TrentinoExampleBasicCalculatorRemoteClientBasicCalculatorRequest_2eproto__INCLUDED
