
/**
 *------------------------------------------------------------------------------------------------
 * (C) Copyright by Siemens Schweiz AG
 *                  BT CPS Control Products & Systems, 2012
 *------------------------------------------------------------------------------------------------
 * SDU Informations  
 *  File                    : SDU_OAM.thrift
 *
 *  Collection Name         : Enum: TP and Web, Product Enums Values
 *  Collection Version 	    : 1.03.000
 *
 *  Generation Request      : Urs Keiser
 *  Generation Date         : 17.08.2012 10:03:37
 *
 *  Report Definition       : Export Bundle Report: [DESIGO v5.1 Data Generation][TP] PXC3 Platform Enumerations (.thrift) {}
 *  Accessor Definition     : /T1000001/O10701/I2000006&
 *  Encoder Definition      : ENC_PXC3_PlatformEnum_v01R00.xquery
 *  Formatter Definition    : FMT_PXC3_PlatformEnum_v01R00.xsl
 *------------------------------------------------------------------------------------------------
 * Description:
 *    This module defines PXC3 platform enumerations in thrift format.
 *------------------------------------------------------------------------------------------------
 * Attention:            This file is generated by the SDU ! 
 *  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *------------------------------------------------------------------------------------------------
 */

namespace java com.siemens.bt.sdu
namespace cpp siemens.bt.sdu
namespace csharp Siemens.BT.SDU
namespace py siemens.bt.sdu
namespace js sdu


enum BA_4139_Widget_Anchoring
{ 
    BA_4139_Top_Left = 0,                                  // Top_Left
	BA_4139_Bottom_Left = 1,                               // Bottom_Left
	BA_4139_Top_Right = 2,                                 // Top_Right
	BA_4139_Bottom_Right = 3                               // Bottom_Right
}

enum BA_4141_Widget_Description_Alignment
{ 
    BA_4141_Not_Visible = 0,                               // Not_Visible
	BA_4141_Single_Line = 1,                               // Single_Line
	BA_4141_Two_Lines = 2                                  // Two_Lines
}

enum BA_4140_Widget_Style
{ 
    BA_4140_Default = 0,                                   // Default
	BA_4140_Invisible = 1,                                 // Invisible
	BA_4140_Red = 2,                                       // Red
	BA_4140_Green = 3,                                     // Green
	BA_4140_Yellow = 4,                                    // Yellow
	BA_4140_Red_Bold = 5,                                  // Red_Bold
	BA_4140_Green_Bold = 6,                                // Green_Bold
	BA_4140_Yellow_Bold = 7,                               // Yellow_Bold
	BA_4140_Blue = 8,                                      // Blue
	BA_4140_Blue_Bold = 9                                  // Blue_Bold
}

enum BA_4147_Automatic_Logout_Timeout
{ 
    BA_4147_Min_05 = 5,                                    // Min_05
	BA_4147_Min_10 = 10,                                   // Min_10
	BA_4147_Min_15 = 15,                                   // Min_15
	BA_4147_Min_30 = 30,                                   // Min_30
	BA_4147_Min_45 = 45,                                   // Min_45
	BA_4147_Min_60 = 60                                    // Min_60
}

enum BA_4143_Web_Server_View_Type
{ 
    BA_4143_Plant_Graphics = 0,                            // Plant_Graphics
	BA_4143_Favorites = 1                                  // Favorites
}

enum BA_4146_Keyboard_Layout
{ 
    BA_4146_Standard = 0,                                  // Standard
	BA_4146_Cyrilic = 1                                    // Cyrilic
}

enum BA_4142_TrendGraph_X_Axis_Resolution
{ 
    BA_4142_All_Trend_Log_Data = 0,                        // All_Trend_Log_Data
	BA_4142_Hours_1 = 1,                                   // Hours_1
	BA_4142_Hours_6 = 2,                                   // Hours_6
	BA_4142_Hours_12 = 3,                                  // Hours_12
	BA_4142_Hours_24 = 4,                                  // Hours_24
	BA_4142_Weeks_1 = 5,                                   // Weeks_1
	BA_4142_Months_1 = 6,                                  // Months_1
	BA_4142_Months_3 = 7                                   // Months_3
}

enum BA_4145_Date_Format
{ 
    BA_4145_DDMMYYYY_Dot = 0,                              // DDMMYYYY_Dot
	BA_4145_DDMMYYYY_Slash = 1,                            // DDMMYYYY_Slash
	BA_4145_DDMMYYYY_Dash = 2,                             // DDMMYYYY_Dash
	BA_4145_YYYYMMDD_Dot = 3,                              // YYYYMMDD_Dot
	BA_4145_YYYYMMDD_Slash = 4,                            // YYYYMMDD_Slash
	BA_4145_YYYYMMDD_Dash = 5,                             // YYYYMMDD_Dash
	BA_4145_MMDDYYYY_Dash = 6,                             // MMDDYYYY_Dash
	BA_4145_MMDDYYYY_Slash = 7                             // MMDDYYYY_Slash
}

enum BA_4144_Time_Format
{ 
    BA_4144_Hours_24 = 0,                                  // Hours_24
	BA_4144_Hours_12 = 1                                   // Hours_12
}

enum BA_1391_GMT_Time_Zones
{ 
    BA_1391_GMT_M_12_00_Kwajalein = 0,                     // GMT_M_12_00_Kwajalein
	BA_1391_GMT_M_11_00_Samoa_Midway = 1,                  // GMT_M_11_00_Samoa_Midway
	BA_1391_GMT_M_10_00_Hawaii = 2,                        // GMT_M_10_00_Hawaii
	BA_1391_GMT_M_09_00_Alaska = 3,                        // GMT_M_09_00_Alaska
	BA_1391_GMT_M_08_00_Pacific_Time = 4,                  // GMT_M_08_00_Pacific_Time
	BA_1391_GMT_M_07_00_Arizona = 5,                       // GMT_M_07_00_Arizona
	BA_1391_GMT_M_07_00_Chihuahua = 6,                     // GMT_M_07_00_Chihuahua
	BA_1391_GMT_M_07_00_Mountain_Time = 7,                 // GMT_M_07_00_Mountain_Time
	BA_1391_GMT_M_06_00_Central_America = 8,               // GMT_M_06_00_Central_America
	BA_1391_GMT_M_06_00_Central_Time = 9,                  // GMT_M_06_00_Central_Time
	BA_1391_GMT_M_06_00_Mexico_City = 10,                  // GMT_M_06_00_Mexico_City
	BA_1391_GMT_M_06_00_Saskatchewan = 11,                 // GMT_M_06_00_Saskatchewan
	BA_1391_GMT_M_05_00_Bogota_Lima = 12,                  // GMT_M_05_00_Bogota_Lima
	BA_1391_GMT_M_05_00_Eastern_Time = 13,                 // GMT_M_05_00_Eastern_Time
	BA_1391_GMT_M_05_00_Indiana_USA = 14,                  // GMT_M_05_00_Indiana_USA
	BA_1391_GMT_M_04_00_Atlantic_Time = 15,                // GMT_M_04_00_Atlantic_Time
	BA_1391_GMT_M_04_00_Caracas_La_Paz = 16,               // GMT_M_04_00_Caracas_La_Paz
	BA_1391_GMT_M_04_00_Santiago = 17,                     // GMT_M_04_00_Santiago
	BA_1391_GMT_M_03_00_Brasilia = 19,                     // GMT_M_03_00_Brasilia
	BA_1391_GMT_M_02_00_Mid_Atlantic = 22,                 // GMT_M_02_00_Mid_Atlantic
	BA_1391_GMT___00_00_London_Dublin_Lisbon = 26,         // GMT___00_00_London_Dublin_Lisbon
	BA_1391_GMT_P_01_00_Berlin_Rome = 27,                  // GMT_P_01_00_Berlin_Rome
	BA_1391_GMT_P_01_00_Budapest_Prague = 28,              // GMT_P_01_00_Budapest_Prague
	BA_1391_GMT_P_01_00_Paris_Madrid = 29,                 // GMT_P_01_00_Paris_Madrid
	BA_1391_GMT_P_01_00_Vienna_Warsaw = 30,                // GMT_P_01_00_Vienna_Warsaw
	BA_1391_GMT_P_02_00_Athens_Istanbul = 32,              // GMT_P_02_00_Athens_Istanbul
	BA_1391_GMT_P_02_00_Bucharest = 33,                    // GMT_P_02_00_Bucharest
	BA_1391_GMT_P_02_00_Cairo = 34,                        // GMT_P_02_00_Cairo
	BA_1391_GMT_P_02_00_Helsinki_Riga = 36,                // GMT_P_02_00_Helsinki_Riga
	BA_1391_GMT_P_02_00_Jerusalem = 37,                    // GMT_P_02_00_Jerusalem
	BA_1391_GMT_P_03_00_Kuwait_Riyadh = 39,                // GMT_P_03_00_Kuwait_Riyadh
	BA_1391_GMT_P_03_00_Moscow = 40,                       // GMT_P_03_00_Moscow
	BA_1391_GMT_P_03_30_Tehran = 42,                       // GMT_P_03_30_Tehran
	BA_1391_GMT_P_04_00_Abu_Dhabi_Muscat = 43,             // GMT_P_04_00_Abu_Dhabi_Muscat
	BA_1391_GMT_P_05_00_Ekaterinburg = 46,                 // GMT_P_05_00_Ekaterinburg
	BA_1391_GMT_P_05_30_New_Delhi = 48,                    // GMT_P_05_30_New_Delhi
	BA_1391_GMT_P_07_00_Bangkok_Jakarta = 54               // GMT_P_07_00_Bangkok_Jakarta
}

enum BA_4148_Customized_View_Ref_Qualifyer
{ 
    BA_4148_Root_Ref = 0,                                  // Root_Ref
	BA_4148_State_Ref = 1,                                 // State_Ref
	BA_4148_Reason_Ref = 2,                                // Reason_Ref
	BA_4148_Switch_Ref = 3,                                // Switch_Ref
	BA_4148_Schedulers_Ref = 4,                            // Schedulers_Ref
	BA_4148_Trends_Ref = 5                                 // Trends_Ref
}
